config/routes.rb
Rails.application.routes.draw do
  resources :product_reviews
  resources :shipmment_items
  resources :shipments
  resources :transactions
  resources :cart_items
  resources :carts
  resources :order_items
  resources :product_categories
  resources :orders
  resources :roles
  resources :user_addresses
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :products, only: [:index, :show, :create, :update, :destroy]
      resources :orders, only: [:index, :show, :create, :destroy, :update]
    end
  end  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user.admin?
      can :manage, :all
    else
      can :read, Product

      # can :read, Order, user_id: user.id
      # cannot :distroy, Order
      # cannot :update, Order

      can :manage, ProductReview, user_id: user.id
      can :read, ProductReview

      #can :read, ProductCategory

      can :manage, UserAddress, user_id: user.id

      can :read, OrderItem

      can :manage, Cart, user_id: user.id

      can :manage, CartItem, user_id: user.id

      can :read, OrderItem

      #can :read, Role

      can :read, Shipment

      can :read, ShipmmentItem


    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :user_address

  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :user_address

  has_many :shipments
  has_many :order_items
  has_many :transactions
  
  enum status: [:placed, :not_placed, :not_set]

  validates :status, presence: :true
  validates :tracking_number, presence: :true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  has_many :shipmment_items
end

app/models/product.rb
class Product < ApplicationRecord

  enum status: [:available, :out_of_stock, :only_few_left, :not_set]

  belongs_to :product_category

  has_many :order_items
  has_many :cart_items
  has_many :product_reviews

  validates :name, presence: :true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord

    has_many :products, :dependent => :destroy

    #validates_associated :products
    #validates :product, presence: true

    #after_touch do |pc|
     #   puts "You have touched an object"
    #end

end

app/models/product_review.rb
class ProductReview < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord

    has_many :users

    
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order

  has_many :shipmment_items
end

app/models/shipmment_item.rb
class ShipmmentItem < ApplicationRecord
  belongs_to :shipment
  belongs_to :order_item
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /([\w+.]+)@[a-z0-9\-.]+\.[a-z]+/i   

  validates :email, presence: true, :uniqueness => { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  
  has_many :user_addresses
  has_many :orders, :dependent => :destroy
  has_many :transactions
  has_many :product_reviews
  has_many :carts

  belongs_to :role

end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user

  has_many :orders
  has_many :carts
end

app/controllers/user_addresses_controller.rb
class UserAddressesController < ApplicationController
  load_and_authorize_resource
  before_action :set_user_address, only: %i[ show edit update destroy ]

  # GET /user_addresses or /user_addresses.json
  def index
    #@user_addresses = UserAddress.all
    @user_addresses = UserAddress.accessible_by(current_ability)
  end

  # GET /user_addresses/1 or /user_addresses/1.json
  def show
  end

  # GET /user_addresses/new
  def new
    @user_address = UserAddress.new
    @users = User.all
  end

  # GET /user_addresses/1/edit
  def edit
    @users = User.all
  end

  # POST /user_addresses or /user_addresses.json
  def create
    @user_address = UserAddress.new(user_address_params)

    respond_to do |format|
      if @user_address.save
        format.html { redirect_to @user_address, notice: "User address was successfully created." }
        format.json { render :show, status: :created, location: @user_address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_addresses/1 or /user_addresses/1.json
  def update
    respond_to do |format|
      if @user_address.update(user_address_params)
        format.html { redirect_to @user_address, notice: "User address was successfully updated." }
        format.json { render :show, status: :ok, location: @user_address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_addresses/1 or /user_addresses/1.json
  def destroy
    @user_address.destroy
    respond_to do |format|
      format.html { redirect_to user_addresses_url, notice: "User address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_address
      @user_address = UserAddress.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_address_params
      params.require(:user_address).permit(:address, :city, :pincode, :state, :country, :phn_no, :residencial_phn_no).merge({user_id: params[:user_id]})
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/user_addresses_helper.rb
module UserAddressesHelper
end

app/views/user_addresses/_form.html.erb
<%= form_with(model: user_address) do |form| %>
  <% if user_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_address.errors.count, "error") %> prohibited this user_address from being saved:</h2>

      <ul>
        <% user_address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control", placeholder: "" %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control", placeholder: "" %>
  </div>

  <div class="field">
    <%= form.label :pincode %>
    <%= form.number_field :pincode, class: "form-control", placeholder: "" %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, class: "form-control", placeholder: "" %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, class: "form-control", placeholder: "" %>
  </div>

  <div class="field">
    <%= form.label :phn_no %>
    <%= form.text_field :phn_no, class: "form-control", placeholder: "" %>
  </div>

  <div class="field">
    <%= form.label :residencial_phn_no %>
    <%= form.text_field :residencial_phn_no, class: "form-control", placeholder: "" %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= select_tag "user_id", options_from_collection_for_select(@users, "id", "email"), class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-secondary"%>
  </div>
<% end %>

app/views/user_addresses/edit.html.erb
<h1>Editing User Address</h1>

<%= render 'form', user_address: @user_address %>

<%= link_to 'Show', @user_address, class: "btn btn-outline-secondary" %> 
<%= link_to 'Back', user_addresses_path, class: "btn btn-outline-dark" %>

app/views/user_addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Addresses</h1>

<table class="table table-striped table-hover table-bordered">
  <thead class= "table-primary">
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>Pincode</th>
      <th>State</th>
      <th>Country</th>
      <th>Phn no.</th>
      <th>Residencial phn no.</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_addresses.each do |user_address| %>
      <tr>
        <td><%= user_address.address %></td>
        <td><%= user_address.city %></td>
        <td><%= user_address.pincode %></td>
        <td><%= user_address.state %></td>
        <td><%= user_address.country %></td>
        <td><%= user_address.phn_no %></td>
        <td><%= user_address.residencial_phn_no %></td>
        <td><%= user_address.user_id %></td>
        <td><%= link_to 'Show', user_address, class: "btn btn-outline-secondary btn-sm" %></td>
        <td><%= link_to 'Edit', edit_user_address_path(user_address), class: "btn btn-outline-secondary btn-sm" %></td>
        <td><%= button_to 'Destroy', user_address, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-secondary btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Address', new_user_address_path, class: "btn btn-outline-secondary" %>

app/views/user_addresses/new.html.erb
<h1>New User Address</h1>

<%= render 'form', user_address: @user_address %>

<%= link_to 'Back', user_addresses_path %>

app/views/user_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @user_address.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @user_address.city %>
</p>

<p>
  <strong>Pincode:</strong>
  <%= @user_address.pincode %>
</p>

<p>
  <strong>State:</strong>
  <%= @user_address.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @user_address.country %>
</p>

<p>
  <strong>Phn no:</strong>
  <%= @user_address.phn_no %>
</p>

<p>
  <strong>Residencial phn no:</strong>
  <%= @user_address.residencial_phn_no %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_address.user_id %>
</p>

<%= link_to 'Edit', edit_user_address_path(@user_address), class: "btn btn-outline-secondary" %> 
<%= link_to 'Back', user_addresses_path, class: "btn btn-outline-dark" %>