config/routes.rb
Rails.application.routes.draw do
  resources :product_reviews
  resources :shipmment_items
  resources :shipments
  resources :transactions
  resources :cart_items
  resources :carts
  resources :order_items
  resources :product_categories
  resources :orders
  resources :roles
  resources :user_addresses
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :products, only: [:index, :show, :create, :update, :destroy]
      resources :orders, only: [:index, :show, :create, :destroy, :update]
    end
  end  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user.admin?
      can :manage, :all
    else
      can :read, Product

      # can :read, Order, user_id: user.id
      # cannot :distroy, Order
      # cannot :update, Order

      can :manage, ProductReview, user_id: user.id
      can :read, ProductReview

      #can :read, ProductCategory

      can :manage, UserAddress, user_id: user.id

      can :read, OrderItem

      can :manage, Cart, user_id: user.id

      can :manage, CartItem, user_id: user.id

      can :read, OrderItem

      #can :read, Role

      can :read, Shipment

      can :read, ShipmmentItem


    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :user_address

  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :user_address

  has_many :shipments
  has_many :order_items
  has_many :transactions
  
  enum status: [:placed, :not_placed, :not_set]

  validates :status, presence: :true
  validates :tracking_number, presence: :true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  has_many :shipmment_items
end

app/models/product.rb
class Product < ApplicationRecord

  enum status: [:available, :out_of_stock, :only_few_left, :not_set]

  belongs_to :product_category

  has_many :order_items
  has_many :cart_items
  has_many :product_reviews

  validates :name, presence: :true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord

    has_many :products, :dependent => :destroy

    #validates_associated :products
    #validates :product, presence: true

    #after_touch do |pc|
     #   puts "You have touched an object"
    #end

end

app/models/product_review.rb
class ProductReview < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord

    has_many :users

    
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order

  has_many :shipmment_items
end

app/models/shipmment_item.rb
class ShipmmentItem < ApplicationRecord
  belongs_to :shipment
  belongs_to :order_item
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /([\w+.]+)@[a-z0-9\-.]+\.[a-z]+/i   

  validates :email, presence: true, :uniqueness => { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  
  has_many :user_addresses
  has_many :orders, :dependent => :destroy
  has_many :transactions
  has_many :product_reviews
  has_many :carts

  belongs_to :role

end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user

  has_many :orders
  has_many :carts
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

  #def logged_in?

  #end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Ecommerce App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
        <% if user_signed_in? %>

          <li class="nav-item">
              <%= button_to 'Home', root_path, :method => :get, class:"nav-link btn btn-outline-link"  %>
          </li>

         <li class="nav-item">
              <%= button_to 'Logout', destroy_user_session_path, :method => :delete, class:"nav-link btn btn-outline-link"  %>
          </li>

          <li class="nav-item">
              <%= button_to 'Edit profile', edit_user_registration_path, :method => :get, class:"nav-link btn btn-outline-link" %>
          </li>
          

          <li class="nav-item">
              <%= button_to 'Products', products_path, :method => :get, class:"nav-link btn btn-outline-link" %>
          </li>

          <li class="nav-item">
                <%= button_to 'Reviews', product_reviews_path, :method => :get, class:"nav-link btn btn-outline-link" %>
          </li>

          <li class="nav-item">
                <%= button_to 'Category', product_categories_path, :method => :get, class:"nav-link btn btn-outline-link" %>
          </li>

          <li class="nav-item">
                <%= button_to 'Order', orders_path, :method => :get, class:"nav-link btn btn-outline-link" %>
          </li>

          <li class="nav-item">
                <%= button_to 'User address', user_addresses_path, :method => :get, class:"nav-link btn btn-outline-link" %>
          </li>

          <li class="nav-item">
                <%= button_to 'ordered items', order_items_path, :method => :get, class:"nav-link btn btn-outline-link" %>
          </li>

          <li class="nav-item">
                <%= button_to 'role', roles_path, :method => :get, class:"nav-link btn btn-outline-link" %>
          </li>

          <li class="nav-item">
                <%= button_to 'shipment', shipments_path, :method => :get, class:"nav-link btn btn-outline-link" %>
          </li>

          <li class="nav-item">
                <%= button_to 'shipment_items', shipmment_items_path, :method => :get, class:"nav-link btn btn-outline-link" %>
          </li>

          <li class="nav-item">
                <%= button_to 'transaction', transactions_path, :method => :get, class:"nav-link btn btn-outline-link" %>
          </li>

          <li class="nav-item">
                <%= button_to 'cart', carts_path, :method => :get, class:"nav-link btn btn-outline-link" %>
          </li>

          <li class="nav-item">
                <%= button_to 'cart_items', cart_items_path, :method => :get, class:"nav-link btn btn-outline-link" %>
          </li>



        <% else %>
          <li class="nav-item">
              <%= button_to 'Sign Up', new_user_registration_path, :method => :get, class:"nav-link btn btn-outline-link" %>
          </li>
          <li class="nav-item">
              <%= button_to 'Log In', new_user_session_path, class:"nav-link btn btn-outline-link" %>
          </li>
        <% end %>
        
      </ul>
      <!-- 
      <% if user_signed_in? %>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      <% end %>

      -->

    </div>
  </div>
</nav>

<!--
<% if user_signed_in? %>
          Welcome, <%=current_user.email%>
<% end %>
--> 

app/views/home/index.html.erb
<h1>Welcome to Ecommerce</h1>
<p>India's top shopping site </p>

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div>
        <img src = "app/assets/images/h1.jpg" width = "300px" height = "300px">
            <div>
                <h4>Philips Hair Dryer </h4>
            </div>
      </div>
    </div>
    <div class="col-md-4">
      Column
    </div>
    <div class="col-md-4">
      Column
    </div>
  </div>
</div>