config/routes.rb
Rails.application.routes.draw do
  resources :product_reviews
  resources :shipmment_items
  resources :shipments
  resources :transactions
  resources :cart_items
  resources :carts
  resources :order_items
  resources :product_categories
  resources :orders
  resources :roles
  resources :user_addresses
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :products, only: [:index, :show, :create, :update, :destroy]
      resources :orders, only: [:index, :show, :create, :destroy, :update]
    end
  end  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user.admin?
      can :manage, :all
    else
      can :read, Product

      # can :read, Order, user_id: user.id
      # cannot :distroy, Order
      # cannot :update, Order

      can :manage, ProductReview, user_id: user.id
      can :read, ProductReview

      #can :read, ProductCategory

      can :manage, UserAddress, user_id: user.id

      can :read, OrderItem

      can :manage, Cart, user_id: user.id

      can :manage, CartItem, user_id: user.id

      can :read, OrderItem

      #can :read, Role

      can :read, Shipment

      can :read, ShipmmentItem


    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :user_address

  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :user_address

  has_many :shipments
  has_many :order_items
  has_many :transactions
  
  enum status: [:placed, :not_placed, :not_set]

  validates :status, presence: :true
  validates :tracking_number, presence: :true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  has_many :shipmment_items
end

app/models/product.rb
class Product < ApplicationRecord

  enum status: [:available, :out_of_stock, :only_few_left, :not_set]

  belongs_to :product_category

  has_many :order_items
  has_many :cart_items
  has_many :product_reviews

  validates :name, presence: :true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord

    has_many :products, :dependent => :destroy

    #validates_associated :products
    #validates :product, presence: true

    #after_touch do |pc|
     #   puts "You have touched an object"
    #end

end

app/models/product_review.rb
class ProductReview < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord

    has_many :users

    
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order

  has_many :shipmment_items
end

app/models/shipmment_item.rb
class ShipmmentItem < ApplicationRecord
  belongs_to :shipment
  belongs_to :order_item
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /([\w+.]+)@[a-z0-9\-.]+\.[a-z]+/i   

  validates :email, presence: true, :uniqueness => { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  
  has_many :user_addresses
  has_many :orders, :dependent => :destroy
  has_many :transactions
  has_many :product_reviews
  has_many :carts

  belongs_to :role

end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user

  has_many :orders
  has_many :carts
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  load_and_authorize_resource

  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    #@carts = Cart.all
    @carts =Cart.accessible_by(current_ability)
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
    @users = User.all
    @user_addresses = UserAddress.all
  end

  # GET /carts/1/edit
  def edit
    @users = User.all
    @user_addresses = UserAddress.all
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.permit(:user_id, :user_address_id)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br />

  <div class="field">
    <%= form.label :user_id %>
    <%= select_tag "user_id", options_from_collection_for_select(@users, "id", "email"), class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :user_address_id %>
    <%= select_tag "user_address_id", options_from_collection_for_select(@user_addresses, "id", "address"), class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart, class: "btn btn-outline-secondary" %> 
<%= link_to 'Back', carts_path, class: "btn btn-outline-dark" %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table class="table table-striped table-hover table-bordered ">
  <thead class="table-primary">
    <tr>
      <th>User</th>
      <th>User address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.user_id %></td>
        <td><%= cart.user_address_id %></td>
        <td><%= link_to 'Show', cart, class: "btn btn-outline-secondary btn-sm" %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart), class: "btn btn-outline-secondary btn-sm" %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-secondary btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path, class: "btn btn-outline-secondary" %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cart.user.email %>
</p>

<p>
  <strong>User address:</strong>
  <%= @cart.user_address.address %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart), class: "btn btn-outline-secondary" %> 
<%= link_to 'Back', carts_path, class: "btn btn-outline-dark" %>