config/routes.rb
Rails.application.routes.draw do
  resources :product_reviews
  resources :shipmment_items
  resources :shipments
  resources :transactions
  resources :cart_items
  resources :carts
  resources :order_items
  resources :product_categories
  resources :orders
  resources :roles
  resources :user_addresses
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :products, only: [:index, :show, :create, :update, :destroy]
      resources :orders, only: [:index, :show, :create, :destroy, :update]
    end
  end  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user.admin?
      can :manage, :all
    else
      can :read, Product

      # can :read, Order, user_id: user.id
      # cannot :distroy, Order
      # cannot :update, Order

      can :manage, ProductReview, user_id: user.id
      can :read, ProductReview

      #can :read, ProductCategory

      can :manage, UserAddress, user_id: user.id

      can :read, OrderItem

      can :manage, Cart, user_id: user.id

      can :manage, CartItem, user_id: user.id

      can :read, OrderItem

      #can :read, Role

      can :read, Shipment

      can :read, ShipmmentItem


    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :user_address

  has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :user_address

  has_many :shipments
  has_many :order_items
  has_many :transactions
  
  enum status: [:placed, :not_placed, :not_set]

  validates :status, presence: :true
  validates :tracking_number, presence: :true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  has_many :shipmment_items
end

app/models/product.rb
class Product < ApplicationRecord

  enum status: [:available, :out_of_stock, :only_few_left, :not_set]

  belongs_to :product_category

  has_many :order_items
  has_many :cart_items
  has_many :product_reviews

  validates :name, presence: :true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord

    has_many :products, :dependent => :destroy

    #validates_associated :products
    #validates :product, presence: true

    #after_touch do |pc|
     #   puts "You have touched an object"
    #end

end

app/models/product_review.rb
class ProductReview < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord

    has_many :users

    
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order

  has_many :shipmment_items
end

app/models/shipmment_item.rb
class ShipmmentItem < ApplicationRecord
  belongs_to :shipment
  belongs_to :order_item
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /([\w+.]+)@[a-z0-9\-.]+\.[a-z]+/i   

  validates :email, presence: true, :uniqueness => { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  
  has_many :user_addresses
  has_many :orders, :dependent => :destroy
  has_many :transactions
  has_many :product_reviews
  has_many :carts

  belongs_to :role

end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user

  has_many :orders
  has_many :carts
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @users = User.all
    @orders = Order.all
  end

  # GET /transactions/1/edit
  def edit
    @users = User.all
    @orders = Order.all
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:mode, :status, :transaction_date, :total_amount).merge({user_id: params[:user_id], order_id: params[:order_id]})
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mode %>
    <%= form.text_field :mode, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :transaction_date %>
    <%= form.date_select :transaction_date, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :total_amount %>
    <%= form.text_field :total_amount, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= select_tag "user_id", options_from_collection_for_select(@users, "id", "email"), class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :order_id %>
    <%= select_tag "order_id", options_from_collection_for_select(@orders, "id", "order_placed_date"), class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction, class: "btn btn-outline-secondary" %> 
<%= link_to 'Back', transactions_path, class: "btn btn-outline-dark" %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table class="table table-striped table-hover table-bordered">
  <thead class= "table-primary">
    <tr>
      <th>Mode</th>
      <th>Status</th>
      <th>Transaction date</th>
      <th>Total amount</th>
      <th>User</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.mode %></td>
        <td><%= transaction.status %></td>
        <td><%= transaction.transaction_date %></td>
        <td><%= transaction.total_amount %></td>
        <td><%= transaction.user_id %></td>
        <td><%= transaction.order_id %></td>
        <td><%= link_to 'Show', transaction, class: "btn btn-outline-secondary btn-sm" %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction), class: "btn btn-outline-secondary btn-sm" %></td>
        <td><%= button_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-secondary btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path, class: "btn btn-outline-secondary" %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mode:</strong>
  <%= @transaction.mode %>
</p>

<p>
  <strong>Status:</strong>
  <%= @transaction.status %>
</p>

<p>
  <strong>Transaction date:</strong>
  <%= @transaction.transaction_date %>
</p>

<p>
  <strong>Total amount:</strong>
  <%= @transaction.total_amount %>
</p>

<p>
  <strong>User Email:</strong>
  <%= @transaction.user.email %>
</p>

<p>
  <strong>Order:</strong>
  <%= @transaction.order.order_placed_date %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction), class: "btn btn-outline-secondary" %> 
<%= link_to 'Back', transactions_path, class: "btn btn-outline-dark" %>